// <auto-generated />
namespace c01103.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class c1103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(c1103));
        
        string IMigrationMetadata.Id
        {
            get { return "201903200758470_c1103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
